### ISSUE TITLE
Add support for spring-cloud-gateway

### ISSUE THREAD

**Issue by bluenux** [spring-projects-experimental/spring-native#1602]
**Describe the issue**
1. route setting application.yml
2. (not native build) run test,  make jar, run jar works.
3. native build success.
4. run error command ``` $ ./target/demo ```

**Steps to reproduce the issue**
1. start.spring.io
2. add spring native, spring cloud gateway
3. generated
4. sample application yml
```
spring:
  cloud:
    gateway:
      routes:
        - id: example
          uri: http://127.0.0.1:8000
          predicates:
            - Path=/
```
5. mvnw -Pnative clean package -DskipTests

**Describe GraalVM and your environment:**
 - GraalVM version : graalvm-ce-java17-22.0.0.2
 - JDK major version: openjdk version "17.0.2"
 - OS: e.g. macOS Monterey
 - Architecture: AMD64

**More details**

```
2022-05-04 20:43:47.216 ERROR 29336 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.cloud.gateway.routes[0].predicates[0]' to org.springframework.cloud.gateway.handler.predicate.PredicateDefinition:

    Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [org.springframework.cloud.gateway.handler.predicate.PredicateDefinition]

Action:

Update your application's configuration

```
